### ISSUE TITLE
cargar las tiendas en db al iniciar proyecto

### ISSUE THREAD

**Issue by vicholp** [AkatsukiTracker/AkatsukiTracker#50]

**Comment by vicholp** [comment]
@LaTortugaR dice que se puede hacer.

**Comment by LaTortugaR** [comment]
Está listo el script, hay un pequeño problema, que es que si una persona está recien iniciando el proyecto tira error dado que no hay columnas de tiendas.

Faltaría que el @VoidRayXX introduzca todas las tiendasen el tiendas.txt

**Comment by VoidRayXX** [comment]
Ya están todas las tiendas en tiendas.txt (en mi rama)

**Comment by LaTortugaR** [comment]
wena, entonces estaríamos, este txt se debe renovarse cuando se agreguen mas tiendas.
