### ISSUE TITLE
ponerle puntos a los precios

### ISSUE THREAD

**Issue by VoidRayXX** [AkatsukiTracker/AkatsukiTracker#64]
$15390000 X
$15.390.000 ✔

**Comment by vicholp** [comment]
@LaTortugaR mira este thread:

[https://stackoverflow.com/questions/1139393/what-is-the-best-django-model-field-to-use-to-represent-a-us-dollar-amount](https://stackoverflow.com/questions/1139393/what-is-the-best-django-model-field-to-use-to-represent-a-us-dollar-amount)

es mejor cambiar el tipo de dato en los modelos parece

**Comment by LaTortugaR** [comment]
probé el decimal field, pero pareciera que no es lo que buscamos, no pone los puntos automaticamente, ademas los pesos chilenos no ocupan decimales. Pareciera hasta ahora que es tema de front, pero intentaré una ultima cosa.

**Comment by LaTortugaR** [comment]
Listo, Django tenía un setting que permitía la separacion automaticamente (USE_THOUSAND_SEPARATOR = True)
