### ISSUE TITLE
Anonymous User

### ISSUE THREAD

**Issue by vicholp** [AkatsukiTracker/AkatsukiTracker#70]
@LaTortugaR que procede

**Comment by LaTortugaR** [comment]
Arreglé el template de trending, tiene un {% if user %}, en el {% else %} solo está el botón de añadir que on click lleva a register

**Comment by LaTortugaR** [comment]
creo que entendi mal el issue, pero salía anonymous user en ciertas paginas, faltaba pasar el parametro de user no mas, ya esta arreglado
